function data()
return {
	en = {
		["mod_name"] = "DB Class 628",
		["mod_desc"] = "Diesel railcars of series 628 of Deutschen Bundesbahn and Deutschen Bahn AG in all existing liveries. Included are the prototype series 628.0 as well as the series 628.2 and 628.4.\n\nAs replacement for the older rail cars and accumulator railcars class 515 the Deutsche Bundesbahn was looking for new types in the early 1970's. They had to be as cost efficient as possible and flexible in usage, e.g. also on main lines. The first prototypes consist of two motorized rail cars, but there power was not very high, else they have been successful. The cars of the series later have been equipped with more powerful engines.\n\nAvailibility: from 1974 until 2005 (628.0) and from 1986 until 2020 (628.2) and from 1992 (628.4), Class 629 is available from 1995 and later. \nMaximum Speed: 120 km/h / 140 km/h\nCapacity:\n628.0: 34\n628.2: 39\n628.4: 42\n629: 44",
        ["br628_menu"] = "Class 628",
		["BR6280"] = "Class 628.0",
		["BR6282"] = "Class 628.2",
		["BR6284"] = "Class 628.4",
        ["BR928"] = "BR 928",
        ["BR6280_desc"] = "Class 628.0 of Deutsche Bundesbahn consisting of two motor cars. ",
        ["BR6280_ob"] = "The prototype series was delivered with automatic Scharfenberg coupling. Livery: turquoise/cream",
		["BR6280_ob2"] = "From 1984 the Scharfenberg couplings have been replaced by standard couplings to be able to add through coaches or couple with other rail cars. Lackierung: turquoise/cream",
        ["BR6280_or"] = "A very few of the 628.0 have been also painted in mint turquoise. Livery: mint turquoise",
        ["BR6280_or_DBAG"] = "A very few of the 628.0 have been also painted in mint turquoise. Livery: mint turquoise of DB AG",
        ["BR6282_desc"] = "Class 628.2 consting of a motor car and a driving car. ",
        ["BR6282_or"] = "Vehicles have been delivered in mint turquoise from 1986. Livery: mint turquoise",
        ["BR6282_or_DBAG"] = "Mint turquoise painted vehicle got updated with the DB AG logo in 1994 before they got repainted in traffic red later. Livery: mint turquoise of DB AG",
        ["BR6282_vr"] = "From 1997 all vehicles have gotten the new actual color concept of Deutsche Bahn. Livery: traffic red",
        ["BR6284_desc"] = "Class 628.4 consting of a motor car and a driving car. ",
        ["BR6284_or"] = "The vehicles have been delivered from 1992 in the colors that have been valid at that time. Livery: mint turquoise",
        ["BR6284_or_DBAG"] = "From 1994 the new delivered vehicles have been branded with new Deutsche Bahn logo or being rebranded still in mint livery. Livery: mint turquoise of DB AG",
        ["BR6284_vr"] = "From 1998 also the newest vehicles from the series got the current actual color concept of Deutsche Bahn. Livery: traffic red",
        ["br628_name"] = "Class 628",
        ["br928_name"] = "Class 928",
        ["BR6284_sylt"] = "Class 628.4 \"Sylt Shuttle plus\"",
		["BR6284_sylt_desc"] = "A unit of class 628.4 drives as Sylt Shuttle plus from Westerland (Sylt) to Bredsted and also Hamburg Altona. The design is special made for this line.",
        ["BR629_name"] = "Class 928",
        ["BR6294_HLB_desc"] = "The HLB 629 072 (VT 72) is one of three original 628/629 diesel railcars. The trains were ordered for the Taunusbahn in 1995 to meet the increasing number of passengers. After 2007, the railcars became less important due to new railcars.",
        ["BR6294_neg_desc"] = "In 2010, neg took over the first class 629 railcar, and more vehicles followed in 2015.",
        ["BR629_DB_desc"] = "Five railcar units based on the 628.4 series, in which both parts of the car were motorized, were procured especially for use on the steep Alzey – Mainz railway.",
	},
	de = {
		["mod_name"] = "DB BR 628",
		["mod_desc"] = "Dieseltriebzüge der Baureihe 628 der Deutschen Bundesbahn und Deutschen Bahn AG in allen existierenden Lackierungen. Enthalten sind die Prototypen der Baureihe 628.0 und ebenso die Serienfahrzeuge des 628.2 und 628.4.\n\nAls Ersatz für die Schienenbusse und die Akkutriebwagen der Baureihe 515 suchte die Deutsche Bundesbahn Anfang der 1970er Jahre neue Fahrzeuge. Diese sollten möglichst kostengünstig sein und flexibel einzusetzen, z.B. auch auf Hauptstrecken. Man konstruierte einen Triebwagen mit zwei Motorwagen, die allerdings recht schwach motorisiert waren. Die Serienbaureihen waren stärker motorisiert.\n\nVerfügbarkeit: ab 1974 bis 2005 (628.0) und ab 1986 bis 2020 (628.2) bzw. ab 1992 (628.4), BR 629 ab 1995 und später \nHöchstgeschwindigkeit: 120 km/h / 140 km/h\nKapazität:\n628.0: 34\n628.2: 39\n628.4: 42\n629: 44",
        ["br628_menu"] = "BR 628",
		["BR6280"] = "BR 628.0",
		["BR6282"] = "BR 628.2",
		["BR6284"] = "BR 628.4",
        ["BR928"] = "BR 928",
        ["BR6280_desc"] = "BR 628.0 der Deutschen Bundesbahn bestehend aus zwei Motorwagen. ",
        ["BR6280_ob"] = "Die Prototypen wurden mit automatischer Scharfenberg-Kupplung ausgeliefert. Lackierung: ozeanblau/beige",
		["BR6280_ob2"] = "Ab 1984 wurden die Scharfenberg-Kupplungen durch Hakenkupplungen ersetzt, um Kurswagen anhängen zu können oder mit anderen Triebwagen kuppeln zu können. Lackierung: ozeanblau/beige",
        ["BR6280_or"] = "Einige wenige 628.0 wurden auch in mintgrün lackiert. Lackierung: minttürkis",
        ["BR6280_or_DBAG"] = "Einige wenige 628.0 wurden auch in mintgrün lackiert. Lackierung: minttürkis der DB AG",
        ["BR6282_desc"] = "Baureihe 628.2 bestehend aus einem Motorwagen und einem Steuerwagen. ",
        ["BR6282_or"] = "Die Fahrzeuge wurden ab 1986 in mintgrün ausgeliefert. Lackierung: minttürkis",
        ["BR6282_or_DBAG"] = "Mintgrüne Fahrzeuge wurden mit dem Logo der DB AG nachgerüstet, bevor sie später in verkehrsrot umlackiert wurden. Lackierung: minttürkis der DB AG",
        ["BR6282_vr"] = "Ab 1997 wurden alle Fahrzeuge in der neuen Lackierung nach und nach umlackiert. Lackierung: verkehrsrot",
        ["BR6284_or"] = "Die Fahrzeuge wurden ab 1992 in der damals gültigen mintgrünen Lackierung ausgeliefert. Lackierung: minttürkis",
        ["BR6282_desc"] = "Baureihe 628.4 bestehend aus einem Motorwagen und einem Steuerwagen. ",
        ["BR6284_or_DBAG"] = "Ab 1994 wurden die mintgrünen Fahrzeuge schon mit dem Logo der DB AG ausgeliefert bzw. nachgeklebt. Lackierung: minttürkis der DB AG",
        ["BR6284_vr"] = "Ab 1998 wurden auch die Fahrzeuge der aktuellsten Baureihe in der neuen Lackierung nach und nach umlackiert. Lackierung: verkehrsrot",
        ["br628_name"] = "BR 628",
        ["br928_name"] = "BR 928",
        ["BR6284_sylt"] = "BR 628.4 \"Sylt Shuttle plus\"",
        ["BR6284_sylt_desc"] = "Eine Einheit der BR 628.4 verkehrt als Sylt Shuttle plus zwischen Westerland (Sylt) und Bredstedt bzw. Hamburg-Altona. Das Design ist eigenständig.",
        ["BR629_name"] = "BR 629",
        ["BR6294_HLB_desc"] = "Der 629 072 (VT 72) der HLB ist einer von ursprünglich drei Dieseltriebwagen der Baureihe 628/629. Die Züge wurden 1995 für die Taunusbahn bestellt um dort den steigenden Fahrgastzahlen gerecht zu werden. Nach 2007 wurden die Triebwagen aufgrund neuer Triebwagen unwichtiger.",
        ["BR6294_neg_desc"] = "Im Jahr 2010 übernahm die neg den ersten Triebwagen der Baureihe 629, im Jahr 2015 folgten weitere Fahrzeuge.",
        ["BR629_DB_desc"] = "Speziell für den Einsatz auf der steigungsreichen Bahnstrecke Alzey–Mainz wurden fünf Triebwageneinheiten auf Basis der Baureihe 628.4 beschafft, bei denen beide Wagenteile motorisiert waren.",
	}
}
end
